student_array = [[80, 70, 90],
                 [60, 85, 75],
                 [95, 88, 92],
                 [70, 60, 65]]

In [1]:
# Computing in Numpy
student_1 = [80, 70, 90]
student_2 = [60, 85, 75]
student_3 = [95, 88, 92]
student_4 = [70, 60, 65]

student = np.array([student_1, student_2, student_3, student_4])

student

NameError: name 'np' is not defined

3.2 **Total Scores per Student (Vector Addition)** 

Compute the total score for each student by summing across the row vector.

student1_total_scores = [80 + 70 + 90] = [240]
student2_total_scores = [60 + 85 + 75] = [220]
student3_total_scores = [95 + 88 + 92] = [275]
student4-total_scores = [70 + 60 + 65] = [195]

total scores = [[240],
                [220],
                [275],
                [195]]

In [ ]:
total_score1 = np.sum(student_1)
total_score2 = np.sum(student_2)
total_score3 = np.sum(student_3)
total_score4 = np.sum(student_4)

print('The sum of the total scores of student 1 is:', total_score1)
print('The sum of the total scores of student 2 is:', total_score2)
print('The sum of the total scores of student 3 is:', total_score3)
print('The sum of the total scores of student 4 is:', total_score4)



The sum of the total scores of student 1 is: 240
The sum of the total scores of student 2 is: 220
The sum of the total scores of student 3 is: 275
The sum of the total scores of student 4 is: 195


**3.3 Applying Weights (Scalar Multiplication)** 

Apply subject weights (e.g., Math is twice as important as others) using scalar 
multiplication.

subject_weight = 2
math_subject_weight = subject_weight * 2

math_scalar_weight = math_subject_weight * [80, 60, 95, 70]
math_scalar_weight = [320, 240, 380, 280]



In [ ]:
math_scalar_weight = np.dot(4, student[:, 0])
english_scalar_weight = np.dot(2, student[:, 1])
science_scalar_weight = np.dot(2, student[:, 2])
print('The subject weight for Mathematics = ',  math_scalar_weight)
print('The subject weight for English = ',  english_scalar_weight)
print('The subject weight for Science = ',  science_scalar_weight)

The subject weight for Mathematics =  [320 240 380 280]
The subject weight for English =  [140 170 176 120]
The subject weight for Science =  [180 150 184 130]


**3.4 Average Score per Subject (Matrix Operations)**
 
Compute the average score for each subject by calculating the column-wise mean. 

In [ ]:
subject_length = len(student[:, 0])
subject_length

4

In [ ]:
math_average_score = sum(student[:, 0] / len(student[:, 0]))
english_average_score = sum(student[:, 1] / len(student[:, 1]))
science_average_score = sum(student[:, 2] / len(student[:, 2]))

print('The average score for Mathematics is:', math_average_score)
print('The average score for English is:', english_average_score)
print('The average score for Science is:', science_average_score)

The average score for Mathematics is: 76.25
The average score for English is: 75.75
The average score for Science is: 80.5


**3.5 Final Grades using Matrix Multiplication**
 
Use matrix multiplication with a weight vector (e.g., [0.5, 0.3, 0.2]) to calculate final grades. 

In [ ]:
weight_vector = np.array([0.6, 0.1, 0.3])

final_grade1 = np.dot(weight_vector, student[0, :])
final_grade2 = np.dot(weight_vector, student[1, :])
final_grade3 = np.dot(weight_vector, student[2, :])
final_grade4 = np.dot(weight_vector, student[3, :])
print(f'The final grades for student 1 is: {final_grade1:.2f}')
print(f'The final grades for student 2 is: {final_grade2:.2f}')
print(f'The final grades for student 3 is: {final_grade3:.2f}')
print(f'The final grades for student 4 is: {final_grade4:.2f}')



The final grades for student 1 is: 82.00
The final grades for student 2 is: 67.00
The final grades for student 3 is: 93.40
The final grades for student 4 is: 67.50


**3.6 Comparing Students (Vector Subtraction) 
Compare two students’ performances by subtracting their score vectors. 

In [ ]:
student_performance = student[0, :] - student[1, :]
student_performance


array([ 20, -15,  15])

### **ADD-ON EXERCISES**

1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total score and the average per subject. 

2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar multiplication and recompute totals.

3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%)Compute final grades using matrix multiplication. 

4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each subject?

**Question 1**

Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total score and the average per subject. 

In [ ]:
matrix = np.random.choice(np.arange(75, 100), size=(5, 4))
print(matrix)

#To compute the total score of each student

for i, row in enumerate(matrix):
        total_score = np.sum(row)
        print(f'The total score of student {i + 1} is {total_score}')


# To compute the average score per  subject
for i, column_index in enumerate(range(matrix.shape[1])):
        average = np.average(matrix[:, column_index])
        subjects = ['Mathematics', 'English', 'Science', 'Biology']
        print(f'The average score of  {subjects[i]} is {average}')

        

[[88 84 84 91]
 [85 89 82 99]
 [98 93 99 80]
 [95 87 83 95]
 [97 76 91 87]]


The total score of student 1 is 347


The total score of student 2 is 355


The total score of student 3 is 370


The total score of student 4 is 360


The total score of student 5 is 351


The average score of  Mathematics is 92.6


The average score of  English is 85.8


The average score of  Science is 87.8


The average score of  Biology is 90.4


np.int64(356)