In [4]:
# import necessary libraries
import numpy as np


In [75]:
# 1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.

range_array = np.random.randint(1,50, size=(6, 6))
print(range_array)


[[ 4 43 21 23 33 48]
 [ 5 13  9 32  2 15]
 [29 24 14  2 17 35]
 [10 15  8 43  6 26]
 [ 8 44 32 11  4 25]
 [47 44 38 25 15 30]]


In [ ]:
# 2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.


# print first two rows
rows = np.array([0, 1])
print("The first two rows are:\n", range_array[rows])

# print last three columns
column1 = range_array[:, -3]
column2 = range_array[:, -2]
column3 = range_array[:, -1]
print("\nThe last three columns are:\n", column1, "\n", column2, "\n", column3)

# print all even numbers in the array
even_numbers = range_array[range_array % 2 == 0]
print("\n The even numbers in the array are:\n", even_numbers)


The first two rows are:
 [[ 4 43 21 23 33 48]
 [ 5 13  9 32  2 15]]

The last three columns are:
 [23 32  2 43 11 25] 
 [33  2 17  6  4 15] 
 [48 15 35 26 25 30]

 The even numbers in the array are:
 [np.int32(2), np.int32(2), np.int32(4), np.int32(4), np.int32(6), np.int32(8), np.int32(8), np.int32(10), np.int32(14), np.int32(24), np.int32(26), np.int32(30), np.int32(32), np.int32(32), np.int32(38), np.int32(44), np.int32(44), np.int32(48)]


In [80]:
# 3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

# Reshape the (3,2,6) into a 3D array
transformed3d = range_array.reshape(3, 2,6)
print("The reshaped form of the array into 3D is:\n", transformed3d)

flattened = transformed3d.flatten()

The reshaped form of the array into 3D is:
 [[[ 4 43 21 23 33 48]
  [ 5 13  9 32  2 15]]

 [[29 24 14  2 17 35]
  [10 15  8 43  6 26]]

 [[ 8 44 32 11  4 25]
  [47 44 38 25 15 30]]]


In [90]:
identity = np.eye(4)
diagonal_number = np.diag([identity, 10, 20, 30, 40]) 
print(diagonal_number)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.