In [1]:
# import necessary libraries
import numpy as np


In [2]:
# 1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.

range_array = np.random.randint(1,50, size=(6, 6))
print(range_array)


[[24 18  5 47 35 21]
 [42 13 18 38 24 45]
 [41 45 18 38 29  7]
 [28  4 43 45 30  3]
 [40 31  5 24 19 10]
 [25 13  4 15 47 17]]


In [3]:
# 2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.


# print first two rows
rows = np.array([0, 1])
print("The first two rows are:\n", range_array[rows])

# print last three columns
column1 = range_array[:, -3]
column2 = range_array[:, -2]
column3 = range_array[:, -1]
print("\nThe last three columns are:\n", column1, "\n", column2, "\n", column3)

# print all even numbers in the array
even_numbers = range_array[range_array % 2 == 0]
print("\n The even numbers in the array are:\n", even_numbers)


The first two rows are:
 [[24 18  5 47 35 21]
 [42 13 18 38 24 45]]

The last three columns are:
 [47 38 38 45 24 15] 
 [35 24 29 30 19 47] 
 [21 45  7  3 10 17]

 The even numbers in the array are:
 [24 18 42 18 38 24 18 38 28  4 30 40 24 10  4]


In [4]:
# 3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

# Reshape the (3,2,6) into a 3D array
transformed3d = range_array.reshape(3, 2,6)
print("The reshaped form of the array into 3D is:\n", transformed3d)

flattened = transformed3d.flatten()

The reshaped form of the array into 3D is:
 [[[24 18  5 47 35 21]
  [42 13 18 38 24 45]]

 [[41 45 18 38 29  7]
  [28  4 43 45 30  3]]

 [[40 31  5 24 19 10]
  [25 13  4 15 47 17]]]


In [5]:
# Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

# create the identity matrix 
identity_matrix = np.eye(4) 
print("This is the 4 x 4 identity matrix:\n", identity_matrix)                                                # create a scalar with with the diagonal numbers will be multiplied

#create a variable to save the diagonal numbers with a step of 10
number = np.arange(10, 41, 10)        

# fill the identity matrix with the new diagonal numbers 
np.fill_diagonal(identity_matrix, number)      
print("\nThis is the identity matrix whose diagonal numbers have been replaced:\n", identity_matrix)




This is the 4 x 4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

This is the identity matrix whose diagonal numbers have been replaced:
 [[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


In [6]:
# 5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)
#  create two range arrays of different shapes
range_array1 = np.random.randint(1,11, size=(3, 4))
range_array2 = np.random.randint(1,11, size=(4, 3))
print("First array:\n", range_array1)
print("\nSecond array:\n", range_array2)

# reshape one of the arrays to allow for multiplication
array1_reshaped = range_array1.reshape(4, 3)
print("\nReshaped first array:\n", array1_reshaped)

# Multiply both arrays
multiplied = array1_reshaped * range_array2
print("\n First array multiplied by second array\n", multiplied)

First array:
 [[4 5 4 1]
 [6 6 2 3]
 [7 8 1 4]]

Second array:
 [[ 1  5  2]
 [ 2  3  2]
 [ 8  6 10]
 [ 1  3  9]]

Reshaped first array:
 [[4 5 4]
 [1 6 6]
 [2 3 7]
 [8 1 4]]

 First array multiplied by second array
 [[ 4 25  8]
 [ 2 18 12]
 [16 18 70]
 [ 8  3 36]]


In [7]:
# 6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

# First create a function to take 2D numpy array as input
def numpy_array(input_numpy):
    # create a copy of the inpu tby flattening
    array_copy = input_numpy.flatten()
    print("The copy of the array enetered is:\n", array_copy)

    # check if there are even numbers in the array 
    even_arrays = array_copy[array_copy % 2 == 0]
    # square the even numbers
    squared_even = pow(even_arrays, 2)
    print("\n The even numbers in the array above are:\n", even_arrays)
    print("\n The square of the even numbers above are:\n", squared_even)


    # check if there are odd numbers in the array
    odd_arrays = array_copy[array_copy % 2 != 0]
    # replace odd numbers with -1
    replaced_odd = array_copy[odd_arrays, -1]
    print("The odd numbers in the array above are:\n", odd_arrays)
    print("The odd numbers have now been replaced with -1:\n", replaced_odd)

number = int(input("Please enter a list of numbers separated by commas for the 2D array"))
list_of_numbers = np.array([number], ndmin=2)



ValueError: invalid literal for int() with base 10: ''

In [ ]:
number = int(input("Please enter a list of numbers separated by commas for the 2D array"))
list_of_numbers = np.array([number])
print(list_of_numbers)